---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: build


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs on Pull Requests
  pull_request:


###
### Generic configuration
###
env:
  NAME: PHP
  MATRIX_VERSION: '["5.2"]'
  MATRIX_ARCH: '["linux/amd64","linux/386"]'


jobs:
  # TODO: This pre-flight setup will be obsolete as soon as this issue has been fixed
  # https://github.com/actions/runner/issues/480
  environment:
    name: Environment
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.set-name.outputs.name }}
      matrix_version: ${{ steps.set-matrix-version.outputs.matrix_version }}
      matrix_arch: ${{ steps.set-matrix-arch.outputs.matrix_arch }}
      matrix_refs: ${{ steps.set-matrix-refs.outputs.matrix_refs }}
    steps:
      - name: "[OUTPUT] Export Name"
        id: set-name
        run: |
          echo '::set-output name=name::${{ env.NAME }}'
          echo "${{ env.NAME }}"
      - name: "[OUTPUT] Export Matrix 'Version'"
        id: set-matrix-version
        run: |
          echo '::set-output name=matrix_version::${{ env.MATRIX_VERSION }}'
          echo "${{ env.MATRIX_VERSION }}"
      - name: "[OUTPUT] Export Matrix 'Arch'"
        id: set-matrix-arch
        run: |
          echo '::set-output name=matrix_arch::${{ env.MATRIX_ARCH }}'
          echo "${{ env.MATRIX_ARCH }}"
      - name: "[OUTPUT] Export Matrix 'Refs'"
        id: set-matrix-refs
        run: |
          echo '::set-output name=matrix_refs::${{ env.MATRIX_REFS }}'
          echo "${{ env.MATRIX_REFS }}"
  docker:
    needs: [environment]
    uses: devilbox/github-actions/.github/workflows/docker-build-multi-arch.yml@master
    with:
      # Only run for forks
      enabled: ${{ github.event.pull_request.head.repo.fork }}
      name: ${{ needs.environment.outputs.name }}
      version: ${{ needs.environment.outputs.matrix_version }}
      arch: ${{ needs.environment.outputs.matrix_arch }}
      refs: ${{ needs.environment.outputs.matrix_refs }}
      can_deploy: false
    secrets:
      dockerhub_username: ""
      dockerhub_password: ""
