---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: nightly


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs daily
  schedule:
    - cron: '0 0 * * *'
    - cron: "*/10 * * * *"


###
### Generic configuration
###
env:
  NAME: PHP
  MATRIX_VERSION: '["5.2"]'
  MATRIX_ARCH: '["linux/amd64","linux/386"]'


jobs:
  # TODO: This pre-flight setup will be obsolete as soon as this issue has been fixed
  # https://github.com/actions/runner/issues/480
  environment:
    name: Environment
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.set-name.outputs.name }}
      matrix_version: ${{ steps.set-matrix-version.outputs.matrix_version }}
      matrix_arch: ${{ steps.set-matrix-arch.outputs.matrix_arch }}
      matrix_refs: ${{ steps.set-matrix-refs.outputs.matrix }}
    steps:
      - name: "[OUTPUT] Export Name"
        id: set-name
        run: |
          echo '::set-output name=name::${{ env.NAME }}'
          echo "${{ env.NAME }}"
      - name: "[OUTPUT] Export Matrix 'Refs' with master and latest tag"
        id: set-matrix-refs
        uses: cytopia/git-ref-matrix-action@v0.1.1
        with:
          repository_default_branch: master
          branches: master
          num_latest_tags: 1
      - name: "[OUTPUT] Export Matrix 'Version'"
        id: set-matrix-version
        run: |
          echo '::set-output name=matrix_version::${{ env.MATRIX_VERSION }}'
          echo "${{ env.MATRIX_VERSION }}"
      - name: "[OUTPUT] Export Matrix 'Arch'"
        id: set-matrix-arch
        run: |
          echo '::set-output name=matrix_arch::${{ env.MATRIX_ARCH }}'
          echo "${{ env.MATRIX_ARCH }}"
  docker:
    needs: [environment]
    uses: devilbox/github-actions/.github/workflows/docker-build-multi-arch.yml@v0.1.0
    with:
      enabled: true
      name: ${{ needs.environment.outputs.name }}
      version: ${{ needs.environment.outputs.matrix_version }}
      arch: ${{ needs.environment.outputs.matrix_arch }}
      refs: ${{ needs.environment.outputs.matrix_refs }}
      # https://help.github.com/en/github/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#functions
      # Only deploy on master, release-* or tags AND only my repo
      can_deploy: ${{ github.event.pull_request.base.repo.id == github.event.pull_request.head.repo.id
        && (
          (github.event_name == 'schedule' && (github.ref == 'refs/heads/master'   || startsWith(github.ref, 'refs/tags/')))
          ||
          (github.event_name == 'push'     && (github.ref == 'refs/heads/master'   || startsWith(github.ref, 'refs/tags/')))
          ||
          (github.event_name == 'push'     && startsWith(github.ref, 'refs/heads/release-'))
        ) }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
